// flow-typed signature: e4827ee134414613b5c222653c14d9cb
// flow-typed version: <<STUB>>/eslint-plugin-chai-friendly_v^0.3.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-chai-friendly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-chai-friendly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-chai-friendly/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-chai-friendly/lib/rules/no-unused-expressions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-chai-friendly/tests/lib/rules/no-unused-expressions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-chai-friendly/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-friendly/lib/index'>;
}
declare module 'eslint-plugin-chai-friendly/lib/rules/no-unused-expressions.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-friendly/lib/rules/no-unused-expressions'>;
}
declare module 'eslint-plugin-chai-friendly/tests/lib/rules/no-unused-expressions.js' {
  declare module.exports: $Exports<'eslint-plugin-chai-friendly/tests/lib/rules/no-unused-expressions'>;
}
